// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        (unknown)
// source: api/proto/gift.proto

package src

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetGiftRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PhoneNumber string `protobuf:"bytes,1,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Code        string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *GetGiftRequest) Reset() {
	*x = GetGiftRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_gift_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGiftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGiftRequest) ProtoMessage() {}

func (x *GetGiftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gift_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGiftRequest.ProtoReflect.Descriptor instead.
func (*GetGiftRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_gift_proto_rawDescGZIP(), []int{0}
}

func (x *GetGiftRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *GetGiftRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GetGiftResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GiftId        int32 `protobuf:"varint,1,opt,name=giftId,proto3" json:"giftId,omitempty"`
	TransactionId int32 `protobuf:"varint,2,opt,name=transactionId,proto3" json:"transactionId,omitempty"`
	Amount        int32 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *GetGiftResponse) Reset() {
	*x = GetGiftResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_gift_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGiftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGiftResponse) ProtoMessage() {}

func (x *GetGiftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gift_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGiftResponse.ProtoReflect.Descriptor instead.
func (*GetGiftResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_gift_proto_rawDescGZIP(), []int{1}
}

func (x *GetGiftResponse) GetGiftId() int32 {
	if x != nil {
		return x.GiftId
	}
	return 0
}

func (x *GetGiftResponse) GetTransactionId() int32 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *GetGiftResponse) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CreateGiftRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount    int32  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Code      string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	BatchSize int32  `protobuf:"varint,3,opt,name=batchSize,proto3" json:"batchSize,omitempty"`
}

func (x *CreateGiftRequest) Reset() {
	*x = CreateGiftRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_gift_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGiftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGiftRequest) ProtoMessage() {}

func (x *CreateGiftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gift_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGiftRequest.ProtoReflect.Descriptor instead.
func (*CreateGiftRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_gift_proto_rawDescGZIP(), []int{2}
}

func (x *CreateGiftRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateGiftRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateGiftRequest) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

type CreateGiftResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateGiftResponse) Reset() {
	*x = CreateGiftResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_gift_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGiftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGiftResponse) ProtoMessage() {}

func (x *CreateGiftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gift_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGiftResponse.ProtoReflect.Descriptor instead.
func (*CreateGiftResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_gift_proto_rawDescGZIP(), []int{3}
}

var File_api_proto_gift_proto protoreflect.FileDescriptor

var file_api_proto_gift_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x69, 0x66, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x69, 0x66, 0x74, 0x22, 0x46, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x47, 0x69, 0x66, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20,
	0x0a, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x22, 0x67, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x47, 0x69, 0x66, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x69, 0x66, 0x74, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x67, 0x69, 0x66, 0x74, 0x49, 0x64, 0x12,
	0x24, 0x0a, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x5d, 0x0a,
	0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x69, 0x66, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x62, 0x61, 0x74, 0x63, 0x68, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x62, 0x61, 0x74, 0x63, 0x68, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x14, 0x0a, 0x12,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x69, 0x66, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x32, 0x86, 0x01, 0x0a, 0x0b, 0x47, 0x69, 0x66, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x36, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x47, 0x69, 0x66, 0x74, 0x12, 0x14, 0x2e,
	0x67, 0x69, 0x66, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x69, 0x66, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x67, 0x69, 0x66, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x69,
	0x66, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x0a, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x47, 0x69, 0x66, 0x74, 0x12, 0x17, 0x2e, 0x67, 0x69, 0x66, 0x74, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x69, 0x66, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x67, 0x69, 0x66, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47,
	0x69, 0x66, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0b, 0x5a, 0x09, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x72, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_gift_proto_rawDescOnce sync.Once
	file_api_proto_gift_proto_rawDescData = file_api_proto_gift_proto_rawDesc
)

func file_api_proto_gift_proto_rawDescGZIP() []byte {
	file_api_proto_gift_proto_rawDescOnce.Do(func() {
		file_api_proto_gift_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_gift_proto_rawDescData)
	})
	return file_api_proto_gift_proto_rawDescData
}

var file_api_proto_gift_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_gift_proto_goTypes = []interface{}{
	(*GetGiftRequest)(nil),     // 0: gift.GetGiftRequest
	(*GetGiftResponse)(nil),    // 1: gift.GetGiftResponse
	(*CreateGiftRequest)(nil),  // 2: gift.CreateGiftRequest
	(*CreateGiftResponse)(nil), // 3: gift.CreateGiftResponse
}
var file_api_proto_gift_proto_depIdxs = []int32{
	0, // 0: gift.GiftService.GetGift:input_type -> gift.GetGiftRequest
	2, // 1: gift.GiftService.CreateGift:input_type -> gift.CreateGiftRequest
	1, // 2: gift.GiftService.GetGift:output_type -> gift.GetGiftResponse
	3, // 3: gift.GiftService.CreateGift:output_type -> gift.CreateGiftResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_gift_proto_init() }
func file_api_proto_gift_proto_init() {
	if File_api_proto_gift_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_gift_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGiftRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_gift_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGiftResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_gift_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGiftRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_gift_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGiftResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_gift_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_gift_proto_goTypes,
		DependencyIndexes: file_api_proto_gift_proto_depIdxs,
		MessageInfos:      file_api_proto_gift_proto_msgTypes,
	}.Build()
	File_api_proto_gift_proto = out.File
	file_api_proto_gift_proto_rawDesc = nil
	file_api_proto_gift_proto_goTypes = nil
	file_api_proto_gift_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GiftServiceClient is the client API for GiftService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GiftServiceClient interface {
	GetGift(ctx context.Context, in *GetGiftRequest, opts ...grpc.CallOption) (*GetGiftResponse, error)
	CreateGift(ctx context.Context, in *CreateGiftRequest, opts ...grpc.CallOption) (*CreateGiftResponse, error)
}

type giftServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGiftServiceClient(cc grpc.ClientConnInterface) GiftServiceClient {
	return &giftServiceClient{cc}
}

func (c *giftServiceClient) GetGift(ctx context.Context, in *GetGiftRequest, opts ...grpc.CallOption) (*GetGiftResponse, error) {
	out := new(GetGiftResponse)
	err := c.cc.Invoke(ctx, "/gift.GiftService/GetGift", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *giftServiceClient) CreateGift(ctx context.Context, in *CreateGiftRequest, opts ...grpc.CallOption) (*CreateGiftResponse, error) {
	out := new(CreateGiftResponse)
	err := c.cc.Invoke(ctx, "/gift.GiftService/CreateGift", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GiftServiceServer is the server API for GiftService service.
type GiftServiceServer interface {
	GetGift(context.Context, *GetGiftRequest) (*GetGiftResponse, error)
	CreateGift(context.Context, *CreateGiftRequest) (*CreateGiftResponse, error)
}

// UnimplementedGiftServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGiftServiceServer struct {
}

func (*UnimplementedGiftServiceServer) GetGift(context.Context, *GetGiftRequest) (*GetGiftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGift not implemented")
}
func (*UnimplementedGiftServiceServer) CreateGift(context.Context, *CreateGiftRequest) (*CreateGiftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGift not implemented")
}

func RegisterGiftServiceServer(s *grpc.Server, srv GiftServiceServer) {
	s.RegisterService(&_GiftService_serviceDesc, srv)
}

func _GiftService_GetGift_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGiftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GiftServiceServer).GetGift(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gift.GiftService/GetGift",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GiftServiceServer).GetGift(ctx, req.(*GetGiftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GiftService_CreateGift_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGiftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GiftServiceServer).CreateGift(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gift.GiftService/CreateGift",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GiftServiceServer).CreateGift(ctx, req.(*CreateGiftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GiftService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gift.GiftService",
	HandlerType: (*GiftServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGift",
			Handler:    _GiftService_GetGift_Handler,
		},
		{
			MethodName: "CreateGift",
			Handler:    _GiftService_CreateGift_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/gift.proto",
}
